name: Spell check release notes
on:
  push:
  pull_request:
    branches: ['main']

jobs:
  spellcheckreleasenotes:
    # if: github.repository_owner == 'Qiskit'
    name: Spell check release notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        name: Install Python
        with:
          python-version: '3.13'
      - name: Install Bpb
        run: |
            curl -fsSL https://bob.ibm.com/download/bobshell.sh | bash
      - name: Spell check
        env:
          BOBSHELL_API_KEY: ${{ secrets.BOBSHELL_API_KEY }}
        run: bob -p "correct the spelling and grammar of @releasenotes/notes/fix-min-point-state-level3.yaml" --yolo
